# Generated by Django 4.1.7 on 2023-11-28 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RequestLogChange",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата")),
                (
                    "change_type",
                    models.CharField(
                        choices=[("create", "Создано"), ("update", "Изменено"), ("delete", "Удалено")],
                        max_length=6,
                        verbose_name="Тип",
                    ),
                ),
                ("instance", models.CharField(max_length=200, verbose_name="Объект")),
                ("fields", models.JSONField(blank=True, null=True, verbose_name="Изменённые поля")),
            ],
            options={
                "verbose_name": "Изменение",
                "verbose_name_plural": "Изменения",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="RequestLogChangeAdmin",
            fields=[],
            options={
                "verbose_name": "Изменение",
                "verbose_name_plural": "Изменения",
                "ordering": ("-created_at",),
                "managed": False,
                "proxy": True,
            },
            bases=("drf_orm_logger.requestlogchange",),
        ),
        migrations.CreateModel(
            name="RequestLogRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата")),
                ("ip", models.GenericIPAddressField(verbose_name="IP")),
                ("method", models.CharField(max_length=7, verbose_name="Метод")),
                ("referer", models.CharField(max_length=1000, verbose_name="Источник")),
                ("url", models.CharField(max_length=1000, verbose_name="Адрес")),
                ("status_code", models.PositiveSmallIntegerField(verbose_name="Код ответа")),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Запись",
                "verbose_name_plural": "Записи",
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddField(
            model_name="requestlogchange",
            name="record",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="changes",
                to="drf_orm_logger.requestlogrecord",
                verbose_name="Запись",
            ),
        ),
    ]
