# Generated by Django 5.0.2 on 2024-05-02 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("drf_orm_logger", "0002_alter_requestlogrecord_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="requestlogchange",
            name="record",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="changes",
                to="drf_orm_logger.requestlogrecord",
                verbose_name="Запись",
            ),
        ),
    ]
