# Generated by Django 5.0.2 on 2024-05-02 16:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("drf_orm_logger", "0003_alter_requestlogchange_record"),
    ]

    operations = [
        migrations.AlterField(
            model_name="requestlogchange",
            name="instance",
            field=models.CharField(db_index=True, max_length=200, verbose_name="Объект"),
        ),
    ]
