# Generated by Django 5.0.2 on 2025-09-09 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_orm_logger', '0004_alter_requestlogchange_instance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestlogchange',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='requestlogrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата'),
        ),
    ]
